name: macOS build (Electron)

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-mac:
    name: Build macOS (${{ matrix.runner }} • ${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner: [macos-13, macos-14]
        arch: [x64, arm64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm install --no-fund --no-audit

      - name: Build (DMG + ZIP)
        run: npx electron-builder --mac dmg zip --${{ matrix.arch }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SeafarNexus-mac-${{ matrix.arch }}
          path: dist/*
          if-no-files-found: error
