name: macOS build (Electron)

on:
  workflow_dispatch:

jobs:
  build:
    name: Build macOS (arm64)
    runs-on: macos-14   # Apple Silicon runner

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Prep npm
        run: |
          npm config set fund false
          npm config set audit false
          npm config set prefer-offline true
          npm config set registry https://registry.npmjs.org/

      - name: Install deps
        run: npm install --no-fund --no-audit

      # ← 這兩段就是你問的，取代原本的 Build/Upload
      - name: Build (DMG only, unsigned)
        run: npx electron-builder --mac dmg --arm64 --publish never

      - name: Upload DMG
        uses: actions/upload-artifact@v4
        with:
          name: SeafarNexus-mac-arm64
          path: dist/*.dmg
          if-no-files-found: error
